version: '3.8'

services:
  main_bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: snippets_bot
    volumes:
      - ./utils:/app/utils
    env_file: .env
    restart: always
